# Generated by Django 4.2.16 on 2025-01-01 15:27

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="file_expiry",
            field=models.DateTimeField(default=chat.models.default_file_expiry),
        ),
    ]
